version: '3'
services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    #environment:
     # MYSQL_ROOT_PASSWORD: root1234
     # MYSQL_DATABASE: superdb
     # MYSQL_USER: ggentil
     # MYSQL_PASSWORD: my1234
    restart: always
    expose:
      - "3306"
    networks:
      - network

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
    environment:
      WP_DATABASE: wpdb
      WP_USER: wpmoi
      WP_PASSWORD: wp1234
    restart: always
    networks:
      - network

  nginx:
    build: ./requirements/nginx
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - "443:443"
    links:
      - wordpress
    networks:
      - network

volumes:
  mariadb_volume:
    driver: local

  wordpress_volume:
    driver: local


networks:
  network:

