version: '3'
services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    restart: always
    expose:
      - "3306"
    networks:
      - network

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    expose:
      - "9000"
    networks:
      - network

  nginx:
    build: ./requirements/nginx
    volumes:
      - wordpress_volume:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - network
    restart: always

volumes:
  mariadb_volume:
    driver: local

  wordpress_volume:
    driver: local


networks:
  network:

