version: '3'
services:
  mariadb:
    image: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: superdb
      MYSQL_USER: ggentil
      MYSQL_PASSWORD: my1234
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    volumes:
      - nginx:/etc/nginx/conf.d
    ports:
      - "443:443"
    links:
      - wordpress

volumes:
  mariadb_volume:
    driver: local
  wordpress_volume:
    driver: local
  nginx:

